#!/usr/bin/env bash
# Install nginx

sudo apt-get update
sudo apt-get install -y nginx
# Configure nginx to listen on port 80
sudo sed -i 's/listen 80 default_server/listen 80/' /etc/nginx/sites-available/default
# Create a custom index.html file that contains the string Hello World!
echo "Hello World!" | sudo tee /var/www/html/index.html
# Restart nginx using service command
sudo service nginx restart
